### ISSUE TITLE
Error while trying to run run_app.py

### ISSUE THREAD

**Issue by nareshnesh** [parulnith/Building-a-Conversational-Chatbot-for-Slack-using-Rasa-and-Python#2]
Traceback (most recent call last):
  File "run_app.py", line 1, in <module>
    from rasa_core.channels.slack import SlackInput
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/channels/__init__.py", line 17, in <module>
    from rasa_core.channels.console import CmdlineInput  # nopep8
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/channels/console.py", line 2, in <module>
    import questionary
  File "/usr/local/lib/python3.5/dist-packages/questionary/__init__.py", line 7, in <module>
    from questionary.prompt import prompt
  File "/usr/local/lib/python3.5/dist-packages/questionary/prompt.py", line 8, in <module>
    from questionary.prompts import AVAILABLE_PROMPTS, prompt_by_name
  File "/usr/local/lib/python3.5/dist-packages/questionary/prompts/__init__.py", line 2, in <module>
    from questionary.prompts import text
  File "/usr/local/lib/python3.5/dist-packages/questionary/prompts/text.py", line 11, in <module>
    from questionary.prompts.common import build_validator
  File "/usr/local/lib/python3.5/dist-packages/questionary/prompts/common.py", line 252, in <module>
    None]
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument

**Comment by visalikk** [comment]
What is the tensorflow version used by this bot? i am getting ModuleNotFoundError: No module named 'tensorflow_core.keras' error while training. Please assist.
